// app/components/Sidebar.tsx
import { useState } from 'react';
import { ChevronRight, ChevronLeft } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { buildTreeData } from '../data/appData';
import { TreeNode } from '../types';
import { getNodeColor } from '../utils/nodeColors';

export function Sidebar() {
  const { visible, selectedId, openPanel, setPanTarget } = useApp();
  const [collapsed, setCollapsed] = useState(
    localStorage.getItem('aura-sidebar-visible') === 'false'
  );
  const [expandedNodes, setExpandedNodes] = useState<Set<string>>(
    new Set()
  );

  const treeData = buildTreeData(visible);

  const toggleNode = (nodeId: string) => {
    const newExpanded = new Set(expandedNodes);
    if (newExpanded.has(nodeId)) {
      newExpanded.delete(nodeId);
    } else {
      newExpanded.add(nodeId);
    }
    setExpandedNodes(newExpanded);
  };

  const handleNodeClick = (node: TreeNode) => {
    if (node.type === 'task') {
      openPanel({ mode: 'task', id: node.id });
    } else {
      openPanel({ mode: 'agent', id: node.id });
    }
    setPanTarget(node.id);
  };

  if (collapsed) {
    return (
      <div className="relative">
        <button
          onClick={() => {
            setCollapsed(false);
            localStorage.setItem('aura-sidebar-visible', 'true');
          }}
          className="absolute left-0 top-24 w-6 h-12 bg-slate-800/80 border border-white/10 border-l-0 rounded-r-md flex items-center justify-center text-slate-400 hover:text-white hover:bg-slate-700/80 transition-all z-10"
          style={{
            backdropFilter: 'blur(8px)',
          }}
        >
          <ChevronRight className="w-4 h-4" />
        </button>
      </div>
    );
  }

  return (
    <aside
      className="w-60 border-r border-white/5 relative flex-shrink-0"
      style={{
        background: 'linear-gradient(to bottom, rgba(15, 23, 42, 0.6), rgba(11, 18, 33, 0.8))',
        backdropFilter: 'blur(8px)',
      }}
    >
      <div className="h-full overflow-y-auto p-4">
        {/* Header card */}
        <div
          className="p-4 rounded-lg border border-white/10 mb-4"
          style={{
            background: 'rgba(15, 23, 42, 0.5)',
          }}
        >
          <h3
            className="text-sm tracking-wider mb-1"
            style={{ fontFamily: 'Syne, sans-serif' }}
          >
            Structure View
          </h3>
          <p className="text-[0.65rem] text-slate-400 leading-relaxed">
            Hierarchical dependency tree
          </p>
        </div>

        {/* Tree */}
        <div className="space-y-1">
          {treeData.map((node) => (
            <TreeNodeItem
              key={node.id}
              node={node}
              expanded={expandedNodes.has(node.id)}
              onToggle={toggleNode}
              selected={selectedId === node.id}
              onSelect={handleNodeClick}
              expandedNodes={expandedNodes}
            />
          ))}
        </div>
      </div>

      {/* Collapse toggle */}
      <button
        onClick={() => {
          setCollapsed(true);
          localStorage.setItem('aura-sidebar-visible', 'false');
        }}
        className="absolute -right-3 top-24 w-6 h-12 bg-slate-800/80 border border-white/10 rounded-r-md flex items-center justify-center text-slate-400 hover:text-white hover:bg-slate-700/80 transition-all"
        style={{
          backdropFilter: 'blur(8px)',
        }}
      >
        <ChevronLeft className="w-4 h-4" />
      </button>
    </aside>
  );
}

interface TreeNodeItemProps {
  node: TreeNode;
  expanded: boolean;
  onToggle: (id: string) => void;
  selected: boolean;
  onSelect: (node: TreeNode) => void;
  expandedNodes: Set<string>;
}

function TreeNodeItem({ node, expanded, onToggle, selected, onSelect, expandedNodes }: TreeNodeItemProps) {
  const hasChildren = node.children && node.children.length > 0;
  const color = getNodeColor(node.type);
  const indent = node.level * 16;

  return (
    <div>
      <button
        onClick={() => onSelect(node)}
        className={`
          w-full text-left px-2 py-1.5 rounded text-xs flex items-center gap-2 transition-all
          ${selected
            ? 'bg-slate-800/60 border'
            : 'hover:bg-slate-800/30'
          }
        `}
        style={{
          paddingLeft: `${indent + 8}px`,
          borderColor: selected ? color.accent : 'transparent',
          boxShadow: selected ? `0 0 8px ${color.glow}` : 'none',
        }}
      >
        {hasChildren && (
          <span
            onClick={(e) => {
              e.stopPropagation();
              onToggle(node.id);
            }}
            className="w-3 h-3 flex items-center justify-center rounded-full bg-slate-700/50 hover:bg-slate-600/50 flex-shrink-0"
          >
            <ChevronRight
              className={`w-2.5 h-2.5 transition-transform ${expanded ? 'rotate-90' : ''}`}
            />
          </span>
        )}
        {!hasChildren && <span className="w-3" />}

        <span
          className="w-1.5 h-1.5 rounded-full flex-shrink-0"
          style={{ backgroundColor: color.accent }}
        />

        <span className="flex-1 truncate text-slate-200">
          {node.label}
        </span>
      </button>

      {hasChildren && expanded && (
        <div>
          {node.children?.map((child) => (
            <TreeNodeItem
              key={child.id}
              node={child}
              expanded={expandedNodes.has(child.id)}
              onToggle={onToggle}
              selected={selected && child.id === node.id}
              onSelect={onSelect}
              expandedNodes={expandedNodes}
            />
          ))}
        </div>
      )}
    </div>
  );
}

// src/lib/components/board/Sidebar.svelte
<script>
  import { visibleNodes } from '$lib/stores/filters.js';
  import { activeId } from '$lib/stores/activeId.js';
  import { openPanel } from '$lib/stores/panel.js';
  import { panTarget } from '$lib/stores/board.js';
  import { AGENTS, SUB_AGENTS, DEVELOPERS } from '$lib/data.js';

  let visible = typeof localStorage !== 'undefined'
    ? localStorage.getItem('aura-sidebar-visible') !== 'false'
    : true;

  $: if (typeof localStorage !== 'undefined') localStorage.setItem('aura-sidebar-visible', visible);

  let openKeys = new Set(
    typeof localStorage !== 'undefined'
      ? JSON.parse(localStorage.getItem('aura-sidebar-open') || '[]')
      : []
  );

  function toggleKey(key) {
    if (openKeys.has(key)) openKeys.delete(key);
    else openKeys.add(key);
    openKeys = openKeys;
    if (typeof localStorage !== 'undefined')
      localStorage.setItem('aura-sidebar-open', JSON.stringify([...openKeys]));
  }

  function onRowClick(id) {
    activeId.set(id);
    openPanel({ mode:'agent', id });
    panTarget.set(id);
  }

  $: tree = $visibleNodes.tasks.map(task => {
    const dev   = DEVELOPERS.find(d => d.id === task.developerId);
    const agent = AGENTS.find(a => a.id === task.agentId);
    const subs  = agent ? SUB_AGENTS.filter(sa => sa.parentId === agent.id) : [];
    const taskKey  = task.id;
    const devKey   = dev   ? `${task.id}|${dev.id}`   : null;
    const agentKey = agent ? `${task.id}|${agent.id}` : null;
    return { task, dev, agent, subs, taskKey, devKey, agentKey };
  });
</script>

<div
<<<<<<< Updated upstream
  class="relative flex-shrink-0 bg-aura-surface border-r border-white/[0.065] flex flex-col transition-[width] duration-[280ms] z-10"
  style="width:{visible?'200px':'0'};overflow:visible"
>
  <!-- Tree content -->
  <div class="flex-1 py-2 overflow-y-auto overflow-x-hidden" style="scrollbar-width:thin">
=======
  class="relative flex-shrink-0 flex flex-col transition-[width] duration-[280ms] z-10"
  style="width:{visible?'clamp(228px,22vw,268px)':'0'};overflow:visible;background:transparent;"
>
  <!-- Tree content -->
  <div class="px-4 pt-4 pb-3">
    <div class="font-syne text-[.7rem] font-bold uppercase tracking-[.18em] text-slate-500 px-1">Structure View</div>
  </div>

  <div class="flex-1 py-4 overflow-y-auto overflow-x-hidden" style="scrollbar-width:thin">
>>>>>>> Stashed changes
    {#each tree as { task, dev, agent, subs, taskKey, devKey, agentKey }}
      <!-- Task row -->
      <div
        class="flex items-center gap-[6px] px-2 py-[5px] mx-1 rounded cursor-pointer text-[.65rem] leading-[1.4] whitespace-nowrap overflow-hidden hover:bg-white/5 transition-colors {$activeId === task.id ? 'bg-white/[.08]' : ''}"
        role="button" tabindex="0"
        on:click={() => onRowClick(task.id)}
        on:keydown={e => e.key==='Enter' && onRowClick(task.id)}
      >
        <span
          class="flex-shrink-0 w-4 h-4 flex items-center justify-center text-[.65rem] text-aura-muted cursor-pointer hover:text-aura-text transition-colors rounded hover:bg-white/10 {!dev ? 'opacity-0 pointer-events-none' : ''}"
          on:click|stopPropagation={() => dev && toggleKey(taskKey)}
          role="button" tabindex="-1"
          on:keydown={e => e.key==='Enter' && dev && toggleKey(taskKey)}
        >{dev ? (openKeys.has(taskKey) ? '▾' : '▸') : '▸'}</span>
        <span class="overflow-hidden text-ellipsis flex-1" style="color:#f59e0b">{task.title}</span>
      </div>

      <!-- Dev children -->
      {#if dev && openKeys.has(taskKey)}
        <div>
          <div
            class="flex items-center gap-[6px] mx-1 rounded cursor-pointer text-[.65rem] leading-[1.4] whitespace-nowrap overflow-hidden hover:bg-white/5 transition-colors {$activeId === dev.id ? 'bg-white/[.08]' : ''}"
            style="padding:5px 8px 5px {8+12}px"
            role="button" tabindex="0"
            on:click={() => onRowClick(dev.id)}
            on:keydown={e => e.key==='Enter' && onRowClick(dev.id)}
          >
            <span
              class="flex-shrink-0 w-4 h-4 flex items-center justify-center text-[.65rem] text-aura-muted cursor-pointer hover:text-aura-text transition-colors rounded hover:bg-white/10 {!agent ? 'opacity-0 pointer-events-none' : ''}"
              on:click|stopPropagation={() => agent && toggleKey(devKey)}
              role="button" tabindex="-1"
              on:keydown={e => e.key==='Enter' && agent && toggleKey(devKey)}
            >{agent ? (openKeys.has(devKey) ? '▾' : '▸') : '▸'}</span>
            <span class="overflow-hidden text-ellipsis flex-1" style="color:#1dd4ef">{dev.name}</span>
          </div>

          <!-- Agent children -->
          {#if agent && openKeys.has(devKey)}
            <div>
              <div
                class="flex items-center gap-[6px] mx-1 rounded cursor-pointer text-[.65rem] leading-[1.4] whitespace-nowrap overflow-hidden hover:bg-white/5 transition-colors {$activeId === agent.id ? 'bg-white/[.08]' : ''}"
                style="padding:5px 8px 5px {8+24}px"
                role="button" tabindex="0"
                on:click={() => onRowClick(agent.id)}
                on:keydown={e => e.key==='Enter' && onRowClick(agent.id)}
              >
                <span
                  class="flex-shrink-0 w-4 h-4 flex items-center justify-center text-[.65rem] text-aura-muted cursor-pointer hover:text-aura-text transition-colors rounded hover:bg-white/10 {!subs.length ? 'opacity-0 pointer-events-none' : ''}"
                  on:click|stopPropagation={() => subs.length && toggleKey(agentKey)}
                  role="button" tabindex="-1"
                  on:keydown={e => e.key==='Enter' && subs.length && toggleKey(agentKey)}
                >{subs.length ? (openKeys.has(agentKey) ? '▾' : '▸') : '▸'}</span>
                <span class="overflow-hidden text-ellipsis flex-1" style="color:#a78bfa">{agent.name}</span>
              </div>

              <!-- Sub-agent children -->
              {#if subs.length && openKeys.has(agentKey)}
                {#each subs as sa}
                  <div
                    class="flex items-center gap-[6px] mx-1 rounded cursor-pointer text-[.65rem] leading-[1.4] whitespace-nowrap overflow-hidden hover:bg-white/5 transition-colors {$activeId === sa.id ? 'bg-white/[.08]' : ''}"
                    style="padding:5px 8px 5px {8+36}px"
                    role="button" tabindex="0"
                    on:click={() => onRowClick(sa.id)}
                    on:keydown={e => e.key==='Enter' && onRowClick(sa.id)}
                  >
                    <span class="flex-shrink-0 w-4 opacity-0">▸</span>
                    <span class="overflow-hidden text-ellipsis flex-1" style="color:#fb7185">{sa.name}</span>
                  </div>
                {/each}
              {/if}
            </div>
          {/if}
        </div>
      {/if}
    {/each}
  </div>

  <!-- Collapse toggle -->
  <button
<<<<<<< Updated upstream
    class="absolute -right-[18px] top-1/2 -translate-y-1/2 w-[18px] h-10 bg-aura-surface border border-white/[0.065] border-l-0 rounded-r-[5px] flex items-center justify-center cursor-pointer text-aura-muted text-[.75rem] z-[11] hover:text-aura-text hover:bg-aura-surface2 select-none transition-colors"
=======
    class="absolute -right-[22px] top-1/2 -translate-y-1/2 w-[22px] h-14 flex items-center justify-center cursor-pointer text-slate-600 text-[.9rem] z-[11] hover:text-slate-300 select-none transition-colors"
>>>>>>> Stashed changes
    on:click={() => visible = !visible}
  >{visible ? '‹' : '›'}</button>
</div>
